name: 'covid19_project'
version: '1.0.0'
config-version: 2


profile: 'snowflake-dw'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"



models:
  covid19_project:
    example:
      materialized: view