version: 2

sources:
  - name: raw_epidemia_c19
    schema: airbyte_schema
    database: AIRBYTE_DATABASE
    description: A replica of the covid19 demographics data from Google BigQuery Open data.
    tables:
      - name: airbyte_index
        columns:
          - name: _airbyte_raw_id
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: airbyte_dados_demograficos
        columns:
          - name: _airbyte_raw_id
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: airbyte_economia
        columns:
          - name: _airbyte_raw_id
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: airbyte_epidemiologia
        columns:
          - name: _airbyte_raw_id
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null



models:
  - name: index
    config:
      materialized: view  

  - name: dados_demograficos
    config:
      materialized: view
    columns:
      - name: location_key
        tests:
          - unique
          - not_null

  - name: economia
    config:
      materialized: view
    columns:
      - name: location_key
        tests:
          - unique
          - not_null
 
  - name: epidemiologia
    config:
      tags: ['daily']
      materialized: view
    columns:
      - name: location_key
        tests:
          - relationships:
              to: ref('base_index')
              field: location_key