version: 2

sources:
    -   name: raw_epidemia_c19
        schema: airbyte_schema
        database: AIRBYTE_DATABASE
        description: Replicacao demografica de dados da covid-19 disponivel no Google BigQuery.
        tables:
            -   name: index
                columns: 
                    -   name: _airbyte_raw_id
                        description: Coluna com hash id pertecentes a cada registro
                        tests:
                            -   unique
                            -   not_null

            -   name: dados_demograficos
                columns:
                    -   name: _airbyte_raw_id
                        description: Coluna com hash id pertecentes a cada registro
                        tests:
                            -   unique
                            -   not_null

            -   name: economia
                columns:
                    -   name: _airbyte_raw_id
                        description: Coluna com hash id pertecentes a cada registro
                        tests:
                            -   unique
                            -   not_null

            -   name: epidemiologia
                columns:
                    -   name: _airbyte_raw_id
                        description: Coluna com hash id pertecentes a cada registro
                        tests:
                            -   unique
                            -   not_null


models:
    -   name: index
        config:
            materialized: view

    -   name: dados_demograficos
        config:
            materialized: view
        columns:
            -   name: location_key
                tests:
                    -   unique
                    -   not_null

    -   name: economia
        config:
            materialized: view
        columns:
            -   name: location_key
                tests:
                    -   unique
                    -   not_null

    -   name: epidemiologia
        config:
            tags: ['daily']
            materialized: view
        columns:
            -   name: location_key
                tests:
                    -   relationships:
                            to: ref('index')
                            field: location_key